title: Jeffrey Yu's Blog
description: Travel blog for Jeffrey Yu
footer_text: Copyright 2021 Jeffrey Yu
header_feature_image: ../uploads/051620_hualien_bus_view.jpg
header_text: Jeffrey's Travel Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
